"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var TypeInfo;
(function (TypeInfo) {
    TypeInfo[TypeInfo["UserDefined"] = 0] = "UserDefined";
    TypeInfo[TypeInfo["SByte"] = 1] = "SByte";
    TypeInfo[TypeInfo["Byte"] = 2] = "Byte";
    TypeInfo[TypeInfo["Boolean"] = 3] = "Boolean";
    TypeInfo[TypeInfo["Int16"] = 4] = "Int16";
    TypeInfo[TypeInfo["UInt16"] = 5] = "UInt16";
    TypeInfo[TypeInfo["Int32"] = 6] = "Int32";
    TypeInfo[TypeInfo["UInt32"] = 7] = "UInt32";
    TypeInfo[TypeInfo["Int64"] = 8] = "Int64";
    TypeInfo[TypeInfo["UInt64"] = 9] = "UInt64";
    TypeInfo[TypeInfo["Single"] = 10] = "Single";
    TypeInfo[TypeInfo["Double"] = 11] = "Double";
    TypeInfo[TypeInfo["String"] = 12] = "String";
    TypeInfo[TypeInfo["Enumeration"] = 13] = "Enumeration";
    TypeInfo[TypeInfo["Vector2I"] = 14] = "Vector2I";
    TypeInfo[TypeInfo["Vector2"] = 15] = "Vector2";
    TypeInfo[TypeInfo["Vector3"] = 16] = "Vector3";
    TypeInfo[TypeInfo["Array"] = 17] = "Array";
    TypeInfo[TypeInfo["Pair"] = 18] = "Pair";
    TypeInfo[TypeInfo["Dictionary"] = 19] = "Dictionary";
    TypeInfo[TypeInfo["List"] = 20] = "List";
    TypeInfo[TypeInfo["HashSet"] = 21] = "HashSet";
    TypeInfo[TypeInfo["Colour"] = 22] = "Colour";
    TypeInfo[TypeInfo["VALUE_MASK"] = 127] = "VALUE_MASK";
    TypeInfo[TypeInfo["IS_GENERIC_TYPE"] = 128] = "IS_GENERIC_TYPE";
})(TypeInfo = exports.TypeInfo || (exports.TypeInfo = {}));
;
//# sourceMappingURL=interfaces.js.map